//SpikeStream includes
#include "NRMRandom.h"
#include "TestNRMRandom.h"
using namespace spikestream;

//Other includes
#include <iostream>
using namespace std;


void TestNRMRandom::init(){
}

void TestNRMRandom::cleanup(){
}


/*! Checks that the random numbers generated by NRMRandom match those generated by the
	original code using a couple of differnet seeds. */
void TestNRMRandom::testRandom(){
	//Test with seed 0
	int expectedRanNums0[] = {7379,4957,1445,2964,1393,6801,3353,3392,596,5684};
	NRMRandom::setSeed(0);
	for(int i=0; i<100; ++i)
		NRMRandom::getRandNum(10000);
	for(int i=0; i<10; ++i)
		QCOMPARE(expectedRanNums0[i], NRMRandom::getRandNum(10000));

	//Test with seed 51
	int expectedRanNums51[] = {54,71,47,90,70,60,91,9,88,20};
	NRMRandom::setSeed(51);
	for(int i=0; i<100; ++i)
		NRMRandom::getRandNum(100);
	for(int i=0; i<10; ++i)
		QCOMPARE(expectedRanNums51[i], NRMRandom::getRandNum(100));
}
