#!/bin/sh
#!/bin/sh
###########################################################################
#                                                                         #
#  SpikeStream Script                                                     #
#  Copyright (C) 2007 by David Gamez                                      #
#   david@davidgamez.eu                                                   #
#   Version 0.1                                                           #
#                                                                         #
#   This program is free software; you can redistribute it and/or modify  #
#   it under the terms of the GNU General Public License as published by  #
#   the Free Software Foundation; either version 2 of the License, or     #
#   (at your option) any later version.                                   #
#                                                                         #
#   This program is distributed in the hope that it will be useful,       #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#   GNU General Public License for more details.                          #
#                                                                         #
#   You should have received a copy of the GNU General Public License     #
#   along with this program; if not, write to the                         #
#   Free Software Foundation, Inc.,                                       #
#   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             #
#                                                                         #
###########################################################################

#-------------------------------- Clean PVM -------------------------------
# Script to reset and clean up after pvm when there have been problems.
#--------------------------------------------------------------------------

#Change to this directory if this script has been invoked from elsewhere
cd $SPIKESTREAM_ROOT/scripts

#Run expect script to shut down pvm
expect CleanPVM_Expect

#Clean up any remaining files
cd /tmp
rm pvm*

echo "PVM cleaned up"










