#!/bin/sh
###########################################################################
#                                                                         #
#  SpikeStream Script                                                     #
#  Copyright (C) 2007 by David Gamez                                      #
#   david@davidgamez.eu                                                   #
#   Version 0.1                                                           #
#                                                                         #
#   This program is free software; you can redistribute it and/or modify  #
#   it under the terms of the GNU General Public License as published by  #
#   the Free Software Foundation; either version 2 of the License, or     #
#   (at your option) any later version.                                   #
#                                                                         #
#   This program is distributed in the hope that it will be useful,       #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#   GNU General Public License for more details.                          #
#                                                                         #
#   You should have received a copy of the GNU General Public License     #
#   along with this program; if not, write to the                         #
#   Free Software Foundation, Inc.,                                       #
#   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             #
#                                                                         #
###########################################################################

#-------------------------- DB File Inspector -----------------------------
#  Looks inside a sql.tar.gz file and outputs a list of the data bases 
#  stored within it.
#--------------------------------------------------------------------------

if [ -z $1 ]
then
echo "Missing file name, exiting"
exit 1
fi

echo "Start files"
tar --list -f $1
echo "End files"

exit 0
