#!/bin/sh
###########################################################################
#                                                                         #
#  SpikeStream Script                                                     #
#  Copyright (C) 2007 by David Gamez                                      #
#   david@davidgamez.eu                                                   #
#   Version 0.1                                                           #
#                                                                         #
#   This program is free software; you can redistribute it and/or modify  #
#   it under the terms of the GNU General Public License as published by  #
#   the Free Software Foundation; either version 2 of the License, or     #
#   (at your option) any later version.                                   #
#                                                                         #
#   This program is distributed in the hope that it will be useful,       #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#   GNU General Public License for more details.                          #
#                                                                         #
#   You should have received a copy of the GNU General Public License     #
#   along with this program; if not, write to the                         #
#   Free Software Foundation, Inc.,                                       #
#   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             #
#                                                                         #
###########################################################################

#---------------------- Save SpikeStream Database -------------------------
#  Dumps a single database to specified file
#  First three parameters are the user, password and host
#  Fourth parameter is the database
#  Fifth is the file where it is to be stored
#  For example: ./SaveSpikeStreamDatabase -uNeuronApp -pSpike 
#                                 -hlocalhost NeuralNetwork foo --compress
#--------------------------------------------------------------------------


#Test for user variable for database, should be something like -uUSER
if [ -z $1 ]
then
echo "Missing user variable, exiting"
exit 1
fi

#Test for password variable for database, should be something like -pPASSWORD
if [ -z $2 ]
then
echo "Missing password variable, exiting"
exit 1
fi

#Test for host variable for database, should be something like -hHOST
if [ -z $3 ]
then
echo "Missing password variable, exiting"
exit 1
fi

#Check the database parameter
if [ -z $4 ]
then
echo "Invalid database: $4"
exit 1
fi

#Check that database file is ok
if [ -n $5 ]
then

#Dump database file
mysqldump $1 $2 $3 --databases $4 -r$4.sql

#Add to archive
tar --remove-files -rf $5.sql.tar $4.sql

else
echo "Invalid database file: $3"
exit 1
fi

#If compresss option has been specified finish off by compressing archive
if [ "$6" = "--compress" ]
then
gzip $5.sql.tar
fi

exit 0


